language: go

go:
  - "1.12.x"

env:
  - GO_ENV=test GO111MODULE=on

services:
  - postgresql

before_script:
  - psql -c 'create database blarden_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: blarden

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get $(go list ./... | grep -v /vendor/)

script: buffalo test
