# use the latest ubuntu environment (18.04) available on travis
dist: xenial
language: go
go:
- 1.13.x
env:
- GO_ENV=test GO111MODULE=on ALLOWED_PHONE_NUMBER='' INTERNAL_API_URL='' API2API_TOKEN='' AES_TOKEN=''
services:
- postgresql
before_script:
- psql -c 'create database blarden_test;' -U postgres
go_import_path: blarden
install:
- go get ./...
script: go test ./...
